# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:alpine
    restart: always
    expose: -"5432"
    ports: "5432:5432"
    environment:
      POSTGRES_DB: typescript-koa 
      #POSTGRES_PASSWORD: example

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"

  environment: 
    ADMINER_DEFAULT_SERVER: database 
    ADMINER_DESIGN: lucas-sandery